services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - "6380:6379"
    networks:
      - my_network

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
    networks:
      - my_network

  celery:
    build:
      context: .
    container_name: celery_worker
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
