"""added another cols to urls table

Revision ID: 177c2b181cb5
Revises: de81f8c9b495
Create Date: 2025-03-22 01:36:11.315150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177c2b181cb5'
down_revision: Union[str, None] = 'de81f8c9b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('date_of_create', sa.TIMESTAMP(), nullable=True))
    op.add_column('urls', sa.Column('last_usage', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'last_usage')
    op.drop_column('urls', 'date_of_create')
    # ### end Alembic commands ###
