"""registered at default changed

Revision ID: 6a671e81e8cb
Revises: b66fc4b8dc63
Create Date: 2025-03-22 00:32:52.212946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a671e81e8cb'
down_revision: Union[str, None] = 'b66fc4b8dc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
