"""added cols to urls table

Revision ID: de81f8c9b495
Revises: 6a671e81e8cb
Create Date: 2025-03-22 01:25:30.527092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de81f8c9b495'
down_revision: Union[str, None] = '6a671e81e8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('urls', sa.Column('count_ref', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'count_ref')
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
